project_id = "qikcbqacbhjhzrcpbupz"
[auth.external.google]
enabled = true
client_id = "871594787799-i2sup14qg9se91svjgcgve64hcg394q2.apps.googleusercontent.com"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
skip_nonce_check = false
